export const charsetConfig = [
  {
    geez: [
      "amharic_1k",
      // "amharic",
      // "amharic_5k"
    ],
  },
  {
    arabic: [
      "arabic_10k",
      // "arabic",
      // "arabic_egypt",
      // "arabic_egypt_1k",
      "kurdish_central_4k",
      // "kurdish_central",
      // "kurdish_central_2k",
      "pashto",
      "persian_5k",
      // "persian",
      // "persian_1k",
      // "persian_20k",
      "urdu_5k",
      // "urdu",
      // "urdu_1k",
    ],
  },
  {
    armenian: [
      "armenian_1k",
      // "armenian",
      "armenian_western_1k",
      // "armenian_western",
    ],
  },
  {
    bengali: [
      "bangla_10k",
      // "bangla",
      // "bangla_letters"
    ],
  },
  {
    cyrillic: [
      "bashkir",
      "belarusian_10k",
      // "belarusian",
      // "belarusian_100k",
      // "belarusian_1k",
      // "belarusian_25k",
      // "belarusian_50k",
      // "belarusian_5k",
      "bulgarian",
      "kazakh_1k",
      // "kazakh",
      "kyrgyz_1k",
      // "kyrgyz",
      "macedonian_10k",
      // "macedonian",
      // "macedonian_1k",
      // "macedonian_75k",
      "mongolian_10k",
      // "mongolian",
      "russian_10k",
      // "russian",
      // "russian_1k",
      // "russian_25k",
      // "russian_375k",
      // "russian_50k",
      // "russian_5k",
      // "russian_abbreviations",
      // "russian_contractions",
      // "russian_contractions_1k",
      "serbian_10k",
      // "serbian",
      "tatar_9k",
      // "tatar",
      // "tatar_1k",
      // "tatar_5k",
      "tatar_crimean_cyrillic_10k",
      // "tatar_crimean_cyrillic",
      // "tatar_crimean_cyrillic_15k",
      // "tatar_crimean_cyrillic_1k",
      // "tatar_crimean_cyrillic_5k",
      "udmurt",
      "ukrainian_10k",
      // "ukrainian",
      // "ukrainian_1k",
      // "ukrainian_50k",
      // "ukrainian_endings",
    ],
  },
  {
    han: [
      "chinese_simplified_10k",
      // "chinese_simplified",
      // "chinese_simplified_1k",
      // "chinese_simplified_50k",
      // "chinese_simplified_5k",
      "chinese_traditional",
    ],
  },
  {
    georgian: ["georgian"],
  },
  {
    greek: [
      "greek_10k",
      // "greek",
      // "greek_1k",
      // "greek_25k",
      // "greek_5k"
    ],
  },
  {
    gujarati: ["gujarati_1k"],
  },
  {
    hebrew: [
      "hebrew_10k",
      // "hebrew",
      // "hebrew_1k",
      // "hebrew_5k",
      "yiddish",
    ],
  },
  {
    devanagari: ["hindi_1k", "marathi", "nepali_1k", "sanskrit"],
  },
  {
    hiragana: ["japanese_hiragana"],
  },
  {
    katakana: ["japanese_katakana"],
  },
  {
    kannada: ["kannada"],
  },
  {
    khmer: ["khmer"],
  },
  {
    hangul: [
      "korean_5k",
      // "korean",
      // "korean_1k"
    ],
  },
  {
    malayalam: ["malayalam"],
  },
  {
    burmese: ["myanmar_burmese"],
  },
  {
    ol_chiki: ["santali"],
  },
  {
    sinhala: ["sinhala"],
  },
  {
    tamil: [
      "tamil_1k",
      // "tamil",
      // "tamil_old"
    ],
  },
  {
    telugu: ["telugu_1k"],
  },
  {
    thai: ["thai_20k"],
  },
  {
    tibetan: ["tibetan_1k"],
  },
  {
    latin: [
      "english_10k",
      // "english",
      // "english_1k",
      // "english_5k",
      // "english_25k",
      // "english_450k",
      // "code_c",
      // "code_cpp",
      // "code_csharp",
      // "code_go",
      // "code_html",
      // "code_java",
      // "code_javascript",
      // "code_lua",
      // "code_php",
      // "code_python",
      // "code_rust",
      // "code_typescript",
      "afrikaans",
      "albanian",
      "catalan",
      "croatian",
      "czech",
      "danish",
      "dutch",
      "estonian",
      "finnish",
      "french",
      "german",
      "hungarian",
      "icelandic",
      "indonesian",
      "italian",
      "latvian",
      "lithuanian",
      "malay",
      "norwegian",
      "polish",
      "portuguese",
      "romanian",
      "slovak",
      "slovenian",
      "spanish",
      "swahili",
      "swedish",
      "tagalog",
      "turkish",
      "vietnamese",
      "welsh",
    ],
  },
];
